package:
  name: "pyradiomics"
  version: "{{ GIT_DESCRIBE_TAG }}"

source:
  path: ../

build:
  number: "{{ GIT_DESCRIBE_NUMBER }}"
  entry_points:
    - pyradiomics=radiomics.scripts.__init__:parse_args

requirements:
  build:
    - {{ compiler('c') }}
    - python >=3.9
    - git
  host:
    - python >=3.9
    - numpy >=2.0
    - pip
    - pykwalify >=1.6.0
    - pywavelets >=1.6.0
    - SimpleITK >=2.4.0
  run:
    - python >=3.9
    - numpy >=2.0
    - pykwalify >=1.6.0
    - pywavelets >=1.6.0
    - SimpleITK >=2.4.0
    - scipy
    - scikit-learn
    - trimesh

about:
  home: http://github.com/Radiomics/pyradiomics#readme
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Radiomics features library for python
  doc_url: https://pyradiomics.readthedocs.io/en/latest/
  dev_url: 

extra:
  recipe-maintainers:
    - JoostJM
    - fedorov
    - pieper
    - hugoaerts
